### ISSUE TITLE
Type information to be shown on any selection

### ISSUE THREAD

**Issue by varosi** [leksah/leksah#85] opened 2015-06-06 13:11 UTC
UX feature request

It will be useful and more easier to use if type information could be shown as a hint (rectangle text field) as close as possible to selected symbol over the source text, and not in separate window far from the symbol. Similar to FP Complete or Visual Studio.
In my opinion this will improve the experience and ease of use.

**Comment by jaccokrijnen** [comment] 2015-09-07 11:07
duplicate of #158

**Closed by jaccokrijnen** 2015-09-07 11:07 UTC
Labels: tool-integration
