### ISSUE TITLE
View -> Group causes leksah to crash, both 0.16 and 0.15.2

### ISSUE THREAD

**Issue by A-Manning** [leksah/leksah#321] opened 2016-08-18 11:40 UTC

**Comment by hamishmack** [comment] 2016-08-23 09:47
Which OS?  When you select this it should show a dialog box asking for the name of the group, does it crash before that?

**Comment by A-Manning** [comment] 2016-08-23 09:51
Tested on Windows 10 and 8.1. 
I don't get the dialog box, just an immediate crash.

**Comment by A-Manning** [comment] 2016-08-23 17:13
Is there somewhere that I can find a crash dump? I'l have a go at fixing the code myself if I can figure out where it's going wrong

**Comment by hamishmack** [comment] 2016-08-23 20:09
Best bet might be to turn on verbose logging.  In a cmd window run:

```
c:
cd c:\Leksah\bin
leksah.exe --verbosity=DEBUG
```

This may give a clue as to what it is doing in the lead up to the crash.  You could also try turning on  some Gtk+ logging with:

```
c:
cd c:\Leksah\bin
set GTK_DEBUG=all
leksah.exe --verbosity=DEBUG
```

Note: GTK_DEBUG=all will make it flash widgets red as they are being redrawn.

I am not sure if `gdb` will work or if there are symbols in the WIndows binaries.  But if you have MSYS2 installed you could try installing `gdb` with `pacman` and running `leksah.exe` in `gdb`.  It might be able to give us a stack trace for the crashing function.

**Comment by A-Manning** [comment] 2016-08-24 08:06
Are you able to reproduce this? All I am doing is loading up leksah, clicking view and then clicking group. No other actions. 

debugging gives some interesting output - 

Verbose logging gave this: 
```
leksah.exe: unsafeCastTo :: invalid conversion from GtkBox to GtkVBox requested.
CallStack (from HasCallStack):
  error, called at src\Data\GI\Base\ManagedPtr.hs:135:7 in haskell-gi-base-0.18-4JqoMdVzTIxGdsbU8e8U7k:Data.GI.Base.ManagedPtr
Segmentation fault/access violation in generated code
Network.Socket.accept: failed (Interrupted function call (WSAEINTR))
Network.Socket.accept: failed (Successful WSAStartup not yet performed (WSANOTINITIALISED))
```

When I ran with Gtk+ logging, I got 

```
Gtk-Message: <interface domain="gtk30">
Gtk-Message: <template class="GtkDialog" parent="GtkWindow">
Gtk-Message: <property name="window_position">
Gtk-Message: </property>
Gtk-Message: <property name="type_hint">
Gtk-Message: </property>
Gtk-Message: <signal name="delete-event" handler="gtk_dialog_delete_event_handler" swapped="no">
Gtk-Message: </signal>
Gtk-Message: <child type="titlebar">
Gtk-Message: set GtkDialog: window-position = ((GtkWindowPosition) GTK_WIN_POS_CENTER_ON_PARENT)
Gtk-Message: set GtkDialog: type-hint = ((GdkWindowTypeHint) GDK_WINDOW_TYPE_HINT_DIALOG)
Gtk-Message: <object class="GtkHeaderBar" id="headerbar">
Gtk-Message: <property name="visible">
Gtk-Message: </property>
Gtk-Message: <property name="show-close-button">
Gtk-Message: </property>
Gtk-Message: </object>
Gtk-Message: created headerbar of type GtkHeaderBar
Gtk-Message: set headerbar: visible = TRUE
Gtk-Message: set headerbar: show-close-button = TRUE
Gtk-Message: </child>
Gtk-Message: adding headerbar to GtkDialog
Gtk-Message: <child>
Gtk-Message: <object class="GtkBox" id="vbox">
Gtk-Message: <property name="visible">
Gtk-Message: </property>
Gtk-Message: <property name="border_width">
Gtk-Message: </property>
Gtk-Message: <property name="orientation">
Gtk-Message: </property>
Gtk-Message: <style>
Gtk-Message: created vbox of type GtkBox
Gtk-Message: set vbox: visible = TRUE
Gtk-Message: set vbox: border-width = 0
Gtk-Message: set vbox: orientation = ((GtkOrientation) GTK_ORIENTATION_VERTICAL)
Gtk-Message: <class name="dialog-vbox">
Gtk-Message: </class>
Gtk-Message: </style>
Gtk-Message: <child>
Gtk-Message: set vbox: orientation = ((GtkOrientation) GTK_ORIENTATION_VERTICAL)
Gtk-Message: set vbox: border-width = 0
Gtk-Message: set vbox: visible = TRUE
Gtk-Message: <object class="GtkBox" id="action_box">
Gtk-Message: <property name="visible">
Gtk-Message: </property>
Gtk-Message: <style>
Gtk-Message: created action_box of type GtkBox
Gtk-Message: set action_box: visible = TRUE
Gtk-Message: <class name="dialog-action-box">
Gtk-Message: </class>
Gtk-Message: </style>
Gtk-Message: <child>
Gtk-Message: set action_box: visible = TRUE
Gtk-Message: <object class="GtkButtonBox" id="action_area">
Gtk-Message: <property name="visible">
Gtk-Message: </property>
Gtk-Message: <property name="layout_style">
Gtk-Message: </property>
Gtk-Message: <property name="hexpand">
Gtk-Message: </property>
Gtk-Message: <style>
Gtk-Message: created action_area of type GtkButtonBox
Gtk-Message: set action_area: visible = TRUE
Gtk-Message: set action_area: layout-style = ((GtkButtonBoxStyle) GTK_BUTTONBOX_END)
Gtk-Message: set action_area: hexpand = TRUE
Gtk-Message: <class name="dialog-action-area">
Gtk-Message: </class>
Gtk-Message: </style>
Gtk-Message: </object>
Gtk-Message: set action_area: hexpand = TRUE
Gtk-Message: set action_area: layout-style = ((GtkButtonBoxStyle) GTK_BUTTONBOX_END)
Gtk-Message: set action_area: visible = TRUE
Gtk-Message: <packing>
Gtk-Message: adding action_area to action_box
Gtk-Message: <property name="pack_type">
Gtk-Message: </property>
Gtk-Message: </packing>
Gtk-Message: </child>
Gtk-Message: </object>
Gtk-Message: <packing>
Gtk-Message: adding action_box to vbox
Gtk-Message: <property name="pack_type">
Gtk-Message: </property>
Gtk-Message: </packing>
Gtk-Message: </child>
Gtk-Message: </object>
Gtk-Message: </child>
Gtk-Message: adding vbox to GtkDialog
Gtk-Message: </template>
Gtk-Message: </interface>
leksah.exe: unsafeCastTo :: invalid conversion from GtkBox to GtkVBox requested.
CallStack (from HasCallStack):
  error, called at src\Data\GI\Base\ManagedPtr.hs:135:7 in haskell-gi-base-0.18-4JqoMdVzTIxGdsbU8e8U7k:Data.GI.Base.ManagedPtr
Segmentation fault/access violation in generated code
```

**Comment by hamishmack** [comment] 2016-08-24 08:18
Oh interesting.  That should have been fixed by this https://github.com/leksah/ltk/commit/8d237f69f46886c361eebca1b0d9a1d35b5ea784

I think we just need to fix the appveyor build so it picks this up.  I'll have a look now.

**Comment by hamishmack** [comment] 2016-08-27 13:35
Please try out the [latest MSI file from appvayor](https://ci.appveyor.com/project/hamishmack/leksah/build/artifacts)

**Comment by A-Manning** [comment] 2016-08-31 14:19
Okay, latest file crashes on launch. 
```
***server start
Bind 127.0.0.1:11111
FileUtils>>getSysLibDir failed with ghc-8.0.1: createProcess: does not exist (No such file or directory)
CallStack (from HasCallStack):
  error, called at src\IDE\Utils\FileUtils.hs:419:35 in leksah-server-0.16.1.0-JTPZ4W9mLy8Dv6E5K7rSRP:IDE.Utils.FileUtils
Finished updating system metadata
Now loading metadata ...
leksah: FileUtils>>getSysLibDir failed with ghc-8.0.1: createProcess: does not exist (No such file or directory)
CallStack (from HasCallStack):
  error, called at src\IDE\Utils\FileUtils.hs:419:35 in leksah-server-0.16.1.0-JTPZ4W9mLy8Dv6E5K7rSRP:IDE.Utils.FileUtils
Segmentation fault/access violation in generated code
```

**Comment by hamishmack** [comment] 2016-09-02 13:14
@A-Manning it looks like it can't find GHC 8.0.1 (`ghc-8.0.1.exe`) in your PATH.  Make sure it is installed and in your PATH.

We need to display a dialog box or something when it is not present.

**Comment by jaccokrijnen** [comment] 2016-09-05 11:34
This seems to be a bigger problem, I have the ghc bin dir in my path and have the same issue:

    leksah.exe: FileUtils>>getSysLibDir failed with ghc-8.0.1: createProcess: does not exist (No such file or directory)

**Comment by hamishmack** [comment] 2016-09-05 12:06
I guess there is no `ghc-8.0.1.exe` for Windows (just `ghc.exe`).

**Comment by jaccokrijnen** [comment] 2016-09-05 12:15
Hm... that's not it

```
Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\Users\Jacco>ghc-8.0.1 --version
The Glorious Glasgow Haskell Compilation System, version 8.0.1

```

**Comment by hamishmack** [comment] 2016-09-05 12:38
Is `ghc-8.0.1.bat` though?

**Comment by hamishmack** [comment] 2016-09-05 12:45
Nope, just checked my VM and it is a `.exe`.

**Comment by hamishmack** [comment] 2016-09-05 13:36
I checked with Process Monitor and it was attempting to open `C:\ProgramData\chocolatey\lib\ghc\tools\ghc-8.0.1\bin\ghc-8.0.1` but not `C:\ProgramData\chocolatey\lib\ghc\tools\ghc-8.0.1\bin\ghc-8.0.1.exe`.  I think the problem is that it does not add the `.exe` extension because the filename `ghc-8.0.1` already includes an extension (`.0.1`).  I have pushed fix that changes `ghc-8.0.1` to `ghc-8.0.1.exe` on windows.  I have to go to bed now though.

**Comment by jaccokrijnen** [comment] 2016-09-05 16:50
I want to test it but for some reason the windows installer crashes on my machine. I think it has to do with the fact that I aborted the uninstaller of the previous leksah because it seemed stuck. Then I tried removing all files of the old leksah, not sure what's wrong.

**Comment by hamishmack** [comment] 2016-09-05 20:50
It fixed it for me.  I did notice on startup it popped up a message about `/home/jacco/leksah.lkshw`, but did open the right workspace in the end.

**Comment by jaccokrijnen** [comment] 2016-09-05 21:15
Oops, I fixed that. I updated the session files to have new users begin with a setup that is probably familiar from other editors/ide's.

**Comment by jaccokrijnen** [comment] 2016-09-05 21:16
The installer works by the way, and no more crashing! @A-Manning can you also confirm if the new version solved it for you as well?

**Closed by jaccokrijnen** 2016-09-05 21:16 UTC
Labels: component:user-interface, type:bug, type:crash

**Comment by jaccokrijnen** [comment] 2016-09-07 09:44
I've added #378
