### ISSUE TITLE
Eval crashes whole IDE

### ISSUE THREAD

**Issue by varosi** [leksah/leksah#87] opened 2015-06-06 13:58 UTC
Leksah 0.15.0.1
Windows 8.1 (x64)

Right click on a function and Eval. It will ask me to run GHCi, I say Run it. Then after loading everything and compiling it crash.

How could I help more for finding the issue?

**Comment by hamishmack** [comment] 2015-06-06 14:53
This is probably a duplicate of #72. Please can you let me know if the work around described there helps?  If so I will include it in the next release.

**Comment by varosi** [comment] 2015-06-08 22:36
Yes, after I deleted those files it is not crashing any more.
Thank you!

2015-06-06 17:53 GMT+03:00 Hamish Mackenzie <notifications@github.com>:

**Closed** 2015-06-08 22:36 UTC
