### ISSUE TITLE
Grep doesn't work under Windows

### ISSUE THREAD

**Issue by varosi** [leksah/leksah#198] opened 2015-09-10 20:33 UTC
Leksah 0.15.1.4

When I press "Grep" button it shows modal dialog with error:
"The program can't start because msys-1.0.dll is missing from your computer. Try reinstalling the program to fix this problem."

So I cannot "Search in Files" in Leksah under Windows.

**Comment by jaccokrijnen** [comment] 2015-09-10 20:45
duplicate of #196

**Closed by jaccokrijnen** 2015-09-10 20:45 UTC
